version: ${VERSION}
services:
  db:
    image: ${IMAGE_NAME}
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORTS}
    networks:
      - custom
    env_file:
      - .env
  db_test:
    image: ${IMAGE_NAME}
    restart: always
    environment:
      - POSTGRES_DB=${DB_TEST_NAME}
      - POSTGRES_USER=${DB_TEST_USER}
      - POSTGRES_PASSWORD=${DB_TEST_PASSWORD}
    ports:
      - ${DB_TEST_PORTS}
    networks:
      - custom
  app:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"

networks:
  custom:
    driver: bridge