version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5444:5444"
    networks:
      - custom
  db_test:
    container_name: "db_test"
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=postgres_test
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
    ports:
      - "5445:5444"
    networks:
      - custom
networks:
  custom:
    driver: bridge