version: "3.8"
services:
  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/user_management_service/app
    env_file:
      - .env
    environment:
      - API_ENVIRONMENT=local
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB={DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORTS}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - custom
    env_file:
      - .env


  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis-data:/var/lib/redis/data
    ports:
      - "6379:6379"


volumes:
    postgres-data:
    postgres-test-data:
    redis-data:


networks:
  custom:
    driver: bridge

