version: "3.8"
services:
  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - app:/user_management_service/app
    env_file:
      - .env
    environment:
      - API_ENVIRONMENT=local
    depends_on:
      - postgres
      - postgres-test
      - localstack
      - redis

  postgres:
    image: postgres:15
    restart: always
    environment:
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=${POSTGRES_DB}
      - PGHOST=${POSTGRES_HOST}
      - PGPORT=${POSTGRES_PORT}
    ports:
      - "5434:5433"
    env_file:
      - .env

  postgres-test:
    image: postgres:15
    restart: always
    environment:
      - PGUSER=${POSTGRES_TEST_USER}
      - PGPASSWORD=${POSTGRES_TEST_PASSWORD}
      - PGDATABASE=${POSTGRES_TEST_DB}
      - PGHOST=${POSTGRES_TEST_HOST}
      - PGPORT=${POSTGRES_TEST_PORT}
    ports:
      - "5435:5434"
    env_file:
      - .env

  redis:
    image: redis:latest
    command: redis-server

    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack
    command: localstack start
    ports:
      - '4566:4566'

volumes:
  app:


