version: "3.8"
services:
  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/user_management_service/app
    env_file:
      - .env
    environment:
      - API_ENVIRONMENT=local
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    restart: always
    environment:
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=${POSTGRES_DB}
      - PGHOST=${POSTGRES_HOST}
      - PGPORT=${POSTGRES_PORT}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  postgres-test:
    image: postgres:15
    restart: always
    environment:
      - PGUSER=${POSTGRES_TEST_USER}
      - PGPASSWORD=${POSTGRES_TEST_PASSWORD}
      - PGDATABASE=${POSTGRES_TEST_DB}
      - PGHOST=${POSTGRES_TEST_HOST}
      - PGPORT=${POSTGRES_TEST_PORT}
    ports:
      - "5434:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    env_file:
      - .env


  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis-data:/var/lib/redis/data
    ports:
      - "6379:6379"


volumes:
    postgres-data:
    postgres-test-data:
    redis-data:
