import os

from dotenv import load_dotenv

load_dotenv()

REAL_DATABASE_URL = os.getenv("REAL_DATABASE_URL")
TEST_DATABASE_URL = os.getenv("TEST_DATABASE_URL")

ACCESS_TOKEN_EXPIRE_MINUTES = os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES")
REFRESH_TOKEN_EXPIRE_MINUTES = os.getenv("REFRESH_TOKEN_EXPIRE_MINUTES")

SECRET_KEY = os.getenv("SECRET_KEY")
ALGORITHM = os.getenv("ALGORITHM")
